### ISSUE TITLE
 Link extension : mdiSvg icon (close) not displayed

### ISSUE THREAD

**Issue by deka** [iliyaZelenko/tiptap-vuetify#95] opened 2019-11-06 16:14 UTC
Hi,

![image](https://user-images.githubusercontent.com/349156/68315912-d5d96c80-00b8-11ea-8f47-084aa637a30a.png)

Regards

**Comment by iliyaZelenko** [comment] 2019-11-06 16:28
Ok, I guessed that there would be such a problem. I will fix it today or tomorrow. Can you please wait?

**Comment by deka** [comment] 2019-11-06 16:50
> Ok, I guessed that there would be such a problem. I will fix it today or tomorrow. Can you please wait?

No problem, i'm not production ready

**Comment by The4thLaw** [comment] 2019-12-07 19:22
It's not limited to mdiSvg, I also have the issue with the mdi icon font.
And I can wait as well :)

Thanks

**Comment by iliyaZelenko** [comment] 2020-02-28 08:36
Looks like this has already been fixed, this is duplicate of this [issue](#130).

**Closed by iliyaZelenko** 2020-02-28 08:36 UTC
Labels: bug, icons
