### ISSUE TITLE
Alignment paragraph

### ISSUE THREAD

**Issue by joweste** [iliyaZelenko/tiptap-vuetify#191] opened 2020-06-04 12:43 UTC
Please,
Where I get a full example with allignment paragraph?
I have search here in the froum and on google.
I found only fragments not working.
I see quill editor has it native. 
But I prefer use tiptap-vuetify.

**Comment by iliyaZelenko** [comment] 2020-09-15 14:22
Duplicate of https://github.com/iliyaZelenko/tiptap-vuetify/issues/218

**Closed by iliyaZelenko** 2020-09-15 14:22 UTC
