### ISSUE TITLE
Bundle size: exceeds the max of 500KB

### ISSUE THREAD

**Issue by tvld** [iliyaZelenko/tiptap-vuetify#160] opened 2020-04-18 09:08 UTC
When building in Nuxt we are getting:
```
ERROR  [BABEL] Note: The code generator has deoptimised the styling of /app/node_modules/tiptap-vuetify/dist/bundle-esm.js as it exceeds the max of 500KB.
```
Is it possible to get that bundle back under the 500K?

**Comment by iliyaZelenko** [comment] 2020-05-08 16:22
Duplicate of #157

**Closed by iliyaZelenko** 2020-05-08 16:22 UTC
