### ISSUE TITLE
Module parse failed: Unexpected token 

### ISSUE THREAD

**Issue by Yaki666** [iliyaZelenko/tiptap-vuetify#170] opened 2020-05-06 05:38 UTC
I have encountered a problem when I `npm run dev` my project. It appears someone has a similar problem but I could not find a solution. What kind of file is webpack not able to load? I am using vue cli to build my product and webpack version is ^3.12.0.
`
Module parse failed: Unexpected token (8886:32)
You may need an appropriate loader to handle this file type.
|           }
| 
|           mergeTarget[prop] = { ...arguments[i][prop],
|             ...mergeTarget[prop]
|           };

 @ ./src/main.js 29:0-53
 @ multi ./node_modules/webpack-dev-server/client?http://0.0.0.0:8081 webpack/hot/dev-server ./src/main.js
`

**Comment by iliyaZelenko** [comment] 2020-05-06 07:58
Duplicate of #106

Most likely this is not the problem of this package, I think. Perhaps a webpack or version of Node.JS.

**Closed by iliyaZelenko** 2020-05-06 07:58 UTC
