### ISSUE TITLE
Could not find a declaration file for module 

### ISSUE THREAD

**Issue by Yaki666** [iliyaZelenko/tiptap-vuetify#164] opened 2020-04-21 09:53 UTC
I am using vue cli. I have installed tiptap-vuetify with npm. When I import it `import  {TiptapVuetifyPlugin} from 'tiptap-vuetify'`, the eslint gives me the error.
```
Could not find a declaration file for module 'tiptap-vuetify'. '/node_modules/tiptap-vuetify/dist/bundle-umd.js' implicitly has an 'any' type.
  Try `npm install @types/tiptap-vuetify` if it exists or add a new declaration (.d.ts) file containing `declare module 'tiptap-vuetify';`ts(7016)
```
and the webpack gives me the error 
```
in ./node_modules/tiptap-vuetify/dist/bundle-esm.js

Module parse failed: Unexpected token (8591:32)
You may need an appropriate loader to handle this file type.
|           }
| 
|           mergeTarget[prop] = { ...arguments[i][prop],
|             ...mergeTarget[prop]
|           };

 @ ./src/main.js 15:0-54
 @ multi ./node_modules/webpack-dev-server/client?http://0.0.0.0:8081 webpack/hot/dev-server ./src/main.js
```
How can I solve the problem?

**Comment by iliyaZelenko** [comment] 2020-05-08 16:08
@Yaki666 hi, did you find a solution Judging by your other issue, you managed to get the project to work.

Duplicate of #106

**Closed by iliyaZelenko** 2020-05-08 16:08 UTC

**Comment by Yaki666** [comment] 2020-05-09 08:11
> @Yaki666 hi, did you find a solution Judging by your other issue, you managed to get the project to work.
> 
> Duplicate of #106

Hi, I just reinstalled my project with vue cli and it works fine now. I think it's the problem of webpack.

**Comment by iliyaZelenko** [comment] 2020-05-09 08:30
Glad to hear that. Good luck with your project. 😄
