### ISSUE TITLE
Table extension

### ISSUE THREAD

**Issue by myalban** [iliyaZelenko/tiptap-vuetify#182] opened 2020-05-23 17:07 UTC
Hi,

This is a fantastic package but I'll like to add Table module extension

You say : "I can easily add more."

So after using the nativeExtensions

`public nativeExtensions = [
    new Table({
      resizable: true
    }),
    new TableHeader(),
    new TableCell(),
    new TableRow()
    })()
  ];`

All seem to be ok, but I can't see the Table button.

How can I add it ?

Thanks

**Comment by iliyaZelenko** [comment] 2020-05-24 10:00
Hi, My sponsor appeared, whose money should come soon. He asked me to add tables, so table support may become available within a week or two.

**Comment by myalban** [comment] 2020-05-24 12:43
nice :)

**Comment by RubenVanEldik** [comment] 2020-05-29 13:35
Hi Ilya, that's great to hear! I just found you package earlier today and one of the only things missing is the table support. I'll be looking forward to this feature!

**Comment by iliyaZelenko** [comment] 2020-06-01 14:30
Duplicate of #20 

New release: https://github.com/iliyaZelenko/tiptap-vuetify/issues/20#issuecomment-636892845

**Closed by iliyaZelenko** 2020-06-01 14:30 UTC
