### ISSUE TITLE
TypeError: Cannot read property 'key' of null

### ISSUE THREAD

**Issue by gokhancetiner** [iliyaZelenko/tiptap-vuetify#38] opened 2019-08-19 16:38 UTC
Hello, 

Thank you for this beautiful component. 

I want to add tiptap-vuetify to my project but when I added the component to my page but when I go to the page I get "TypeError: Cannot read property 'key' of null" error. Do you have any idea why that can happen ?

Many Thanks

**Comment by iliyaZelenko** [comment] 2019-08-19 19:05
Hi,

Thank you for taking a look at this package.

Perhaps this is somehow related to the `Link` extension? Do you use Vuetify 2 or 1? 
I think this error is from [this line](https://github.com/iliyaZelenko/tiptap-vuetify/blob/master/src/components/Bubble.vue#L112).

This package is poorly tested on the Vuetify 2. I started making a new version in which I completely reworked the code and will support Vuetify 2, but I don’t have enough time to finish and release it. I think from next week I will be more actively working on this package, so I’ll finish it.

Maybe you should try another package, thanks again for your attention.

**Comment by gokhancetiner** [comment] 2019-08-20 09:37
Hello @iliyaZelenko ,

I use Vuetify 1.3.14 and nuxt 2.3.4 so it is not related to new Vuetify version. If you need more detail to investigate I try to provide you. 

Thanks

**Comment by iliyaZelenko** [comment] 2019-08-20 09:55
Actually this package seems to work badly with version below 1.4, there was a problem too: #9
Maybe you just need to upgrade to at least to 1.4

If you can’t do this, then it would be cool if you showed the code that you use and is associated with this package. In what place in my code this error will also help (you can look at _stack trace_)

**Comment by iliyaZelenko** [comment] 2019-10-09 21:10
I will close this because your version `1.4` is a very old version of Vuetify. I am happy to help if there are more clarifications.

**Closed by iliyaZelenko** 2019-10-09 21:10 UTC
Labels: bug, vuetify < 1.4

**Comment by abdelkarim22** [comment] 2019-11-28 11:21
First of all thank you @iliyaZelenko for this nice work.I know this issue is closed but even with a version greater than 1.4 I still get this error. Any help would be very appreciated?

**Comment by iliyaZelenko** [comment] 2019-11-28 13:34
@abdelkarim22 It’s strange, because other people don’t have such a error. 

Perhaps you have some kind of unusual environment. Or you are not using the package as shown in the instructions, could you give your code? 

Also, can you, please, show in DevTools in which specific place in the code the error occurs?

Sorry for the inconvenience, I want to help you as soon as possible.

**Comment by abdelkarim22** [comment] 2019-12-02 12:28
Thank you very much for your quick answer.I am running my application using stable version of nodejs.
let me give you the packages I used here and their versions:
1- nodejs v10.15.3
2- vue : "^2.5.17"
3- vuetify : 1.5.14
4- tiptap-vuetify: 1.5.0

I am going to give you the way I tried to integrate your package to my application:

1. created a plugin called tiptap.js and this is what it includes:
`import Vue from 'vue';
import Vuetify from 'vuetify';
import { TiptapVuetifyPlugin } from 'tiptap-vuetify';
// don't forget to import styles
import 'tiptap-vuetify/dist/main.css';

// first it
Vue.use(Vuetify);

Vue.use(TiptapVuetifyPlugin, {});
`
2. I imported that plugin inside my main.js normally:
`import './plugins/tiptap';`

3.created a vue component and inserted your code inside it.
`<template>
  <div>
    
    <tiptap-vuetify
      v-model="content"
      :extensions="extensions"
    />

    
    <h1>Preview</h1>
    <hr>

    <div
      class="tiptap-vuetify-editor__content"
      v-html="content"
    />
  </div>
</template>

<script>
// import the component and the necessary extensions
import { TiptapVuetify, Heading, Bold, Italic, Strike, Underline, Code, CodeBlock, Paragraph, BulletList, OrderedList,
  ListItem, Link, Blockquote, HardBreak, HorizontalRule,
} from 'tiptap-vuetify'

export default {
  components: { TiptapVuetify },
  data() {
    return {
      extensions: [
        new Heading({
          levels: [1, 2, 3]
        }),
        new Bold(),
        new Italic(),
        new Strike(),
        new Underline(),
        new Code(),
        new CodeBlock(),
        new Paragraph(),
        new BulletList(),
        new OrderedList(),
        new ListItem(),
        new Link(),
        new Blockquote(),
        new HardBreak(),
        new HorizontalRule(),
      ],
      // starting content for the editor
      content: `
        <h1>Yay Headlines!</h1>
        <p>All these <strong>cool tags</strong> are working now.</p>
      `
    };
  },
}
</script>`

lastly I imported that component inside my page.and I get this error:
![image](https://user-images.githubusercontent.com/20290729/69959498-58b6e100-1518-11ea-8870-b69d822aa59d.png)

**Comment by iliyaZelenko** [comment] 2019-12-02 22:29
Thank you for providing detailed information. Immediately I saw you had an error in the code, this line:

``` js
Vue.use(TiptapVuetifyPlugin, {});
```

Here is an example of the code that is written in the instructions (`README.md`):

> ``` js
> Vue.use(TiptapVuetifyPlugin, {
>   // the next line is important! You need to provide the Vuetify Object to this place.
>   vuetify, // same as "vuetify: vuetify"
>   // optional, default to 'md' (default vuetify icons before v2.0.0)
>   iconsGroup: 'md'
> })
> ```

Pay attention to
> // the next line is important! You need to provide the Vuetify Object to this place.

If you do like this, then the problem should disappear. Perhaps my documentation is not clear enough, what do you think?

**Comment by abdelkarim22** [comment] 2019-12-05 08:06
I am using your documentation for vuetify version 1.x 
![image](https://user-images.githubusercontent.com/20290729/70215739-30fd8e00-174f-11ea-91b4-e02838dd2d93.png)

as you have shown here.What you wrote above is I think for vuetify version 2.x ? I do not think that the problem is solved yet

**Comment by iliyaZelenko** [comment] 2019-12-06 21:53
For some reason I thought you had a 2.x version. Then it is interesting. 

Could you please click on these links and show which code will open to you?

![69959783-fdd1b980-1518-11ea-9a22-2bd08e47e4b2](https://user-images.githubusercontent.com/13103045/70358929-30feaa80-1883-11ea-8a3f-c60144255aea.png)

**Comment by abdelkarim22** [comment] 2019-12-09 07:11
![Screenshot_5](https://user-images.githubusercontent.com/20290729/70414759-07ed3e00-1a6c-11ea-9af9-9b483af19dc9.png)


this is what I get.I made sure my nodejs version and other versions are stable so I wont have any problem but this still nasty one.

**Comment by guillaumesoul** [comment] 2021-03-04 14:25
I'm facing the exact same issue, any ideas how to solve it?
