### ISSUE TITLE
Show img base64 and tables

### ISSUE THREAD

**Issue by fabioebner** [iliyaZelenko/tiptap-vuetify#31] opened 2019-07-30 00:00 UTC
I man, I know that are not possible to add table and images yet, but if my table and image come from a html (template), there is not possible to show, but not modify?

tks

**Comment by iliyaZelenko** [comment] 2019-07-31 08:34
Hi. I did not fully understand the question. You need the table to be displayed in the editor, but it could not be edited? (cells)

I'm not sure that now the tables will work at all if I do not have their support. I would be very happy to make support as soon as possible, but I have affairs at work. But this project will not be abandoned, I will deal with it as soon as I find the time. I apologize for that.

**Comment by iliyaZelenko** [comment] 2019-10-13 00:20
Image support can be added via https://github.com/iliyaZelenko/tiptap-vuetify#native-extensions
You can add any extensions this way.

This question is a duplicate of the this two: https://github.com/iliyaZelenko/tiptap-vuetify/issues/16 https://github.com/iliyaZelenko/tiptap-vuetify/issues/20, so I close it.

**Closed by iliyaZelenko** 2019-10-13 00:20 UTC
Labels: enhancement, question
